import { existsSync, mkdirSync, writeFileSync, chmodSync } from 'node:fs';
import { join } from 'node:path';

export function installGitHook(repoPath: string): void {
  const hooksDir = join(repoPath, '.git', 'hooks');
  const hookPath = join(hooksDir, 'prepare-commit-msg');

  // Check if .git directory exists
  if (!existsSync(join(repoPath, '.git'))) {
    throw new Error('Not a git repository. Run this command from the root of a git repository.');
  }

  // Create hooks directory if it doesn't exist
  if (!existsSync(hooksDir)) {
    mkdirSync(hooksDir, { recursive: true });
  }

  // Hook script that calls clg generate
  const hookContent = `#!/bin/sh
# commit-lint-gen hook
# Auto-generated by clg init

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

# Only run for regular commits (not merges, amends, etc.)
if [ -z "$COMMIT_SOURCE" ]; then
  clg generate "$COMMIT_MSG_FILE"
fi
`;

  // Write the hook file
  writeFileSync(hookPath, hookContent, { mode: 0o755 });

  // Ensure it's executable (important for Unix-like systems)
  try {
    chmodSync(hookPath, 0o755);
  } catch (error) {
    // chmod might fail on Windows, but that's okay
  }

  console.log('✓ Git hook installed successfully!');
  console.log(`  Location: ${hookPath}`);
  console.log('\nThe hook will run automatically on git commit.');
}

export function uninstallGitHook(repoPath: string): void {
  const hookPath = join(repoPath, '.git', 'hooks', 'prepare-commit-msg');

  if (!existsSync(hookPath)) {
    console.log('No git hook found to uninstall.');
    return;
  }

  // Check if it's our hook before removing
  const fs = require('node:fs');
  const content = fs.readFileSync(hookPath, 'utf-8');

  if (!content.includes('commit-lint-gen hook')) {
    throw new Error('The prepare-commit-msg hook was not installed by clg. Please remove it manually if needed.');
  }

  fs.unlinkSync(hookPath);
  console.log('✓ Git hook uninstalled successfully!');
}
